FROM gitlab/gitlab-runner:latest

# To build the image:
# docker build -f ./services/gitlab_runner/Dockerfile -t my-gitlab-runner:20250112_0900 ./services/gitlab_runner/

# To save the image:
# docker save my-gitlab-runner:20250112_0900 | gzip > ./docker_image/my-gitlab-runner_20250112_0900.tar.gz