FROM ghcr.io/joeferner/redis-commander:latest

# To build the image:
# docker build -f ./services/redis_ui/Dockerfile -t my-redis-ui:20250112_0900 ./services/redis_ui/

# To save the image:
# docker save my-redis-ui:20250112_0900 | gzip > ./docker_image/my-redis-ui_20250112_0900.tar.gz