FROM gitea/gitea:latest

# To build the image:
# docker build -f ./services/gitea/Dockerfile -t my-gitea:20251217_0900 ./services/gitea/

# To save the image:
# docker save my-gitea:20251217_0900 | gzip > ./docker_image/my-gitea_20251217_0900.tar.gz