FROM sosedoff/pgweb:latest

# To build the image:
# docker build -f ./services/postgres_ui/Dockerfile -t my-postgres-ui:20251217_0900 ./services/postgres_ui/

# To save the image:
# docker save my-postgres-ui:20251217_0900 | gzip > ./docker_image/my-postgres-ui_20251217_0900.tar.gz