FROM gitea/act_runner:latest

# To build the image:
# docker build -f ./services/gitea_runner/Dockerfile -t my-gitea-runner:20251217_0900 ./services/gitea_runner/

# To save the image:
# docker save my-gitea-runner:20251217_0900 | gzip > ./docker_image/my-gitea-runner_20251217_0900.tar.gz